In [1]:
import pandas as pd
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import itertools
from sklearn.metrics import classification_report, plot_confusion_matrix
import seaborn as sns

In [2]:
data = pd.read_csv("wine_quality.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed.acidity         6497 non-null   float64
 1   volatile.acidity      6497 non-null   float64
 2   citric.acid           6497 non-null   float64
 3   residual.sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free.sulfur.dioxide   6497 non-null   float64
 6   total.sulfur.dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 609.2 KB


## Divisão de base de dados e separação de base

In [3]:
#attributes = data[["fixed.acidity","volatile.acidity","citric.acid","residual.sugar","chlorides","free.sulfur.dioxide","total.sulfur.dioxide","density","pH","sulphates","alcohol"]]
#quality = data[["quality"]]

In [4]:
attributes = data.iloc[:, 0:11].values
quality = data.iloc[:, 11].values

quality_dummy = np_utils.to_categorical(quality)

X_train, X_test, y_train, y_test =  train_test_split(attributes, quality_dummy)

In [13]:
classifier = Sequential()
classifier.add(Dense(units=32, activation="linear",input_dim=11))
classifier.add(Dropout(0.1))
classifier.add(Dense(units=16, activation="linear"))
classifier.add(Dropout(0.1))
classifier.add(Dense(units=10, activation="softmax"))
classifier.compile(optimizer="adam", loss="categorical_crossentropy",
                      metrics=["categorical_accuracy"])
history = classifier.fit(X_train, y_train, batch_size=32,
                  epochs=50,validation_split=0.1)

Epoch 1/50
137/137 [==============================] - 1s 2ms/step - loss: 11.1902 - categorical_accuracy: 0.3029 - val_loss: 2.9136 - val_categorical_accuracy: 0.4447
Epoch 2/50
137/137 [==============================] - 0s 2ms/step - loss: 5.3200 - categorical_accuracy: 0.3271 - val_loss: 1.9219 - val_categorical_accuracy: 0.4693
Epoch 3/50
137/137 [==============================] - 0s 2ms/step - loss: 3.4706 - categorical_accuracy: 0.3305 - val_loss: 1.5232 - val_categorical_accuracy: 0.4631
Epoch 4/50
137/137 [==============================] - 0s 1ms/step - loss: 2.4551 - categorical_accuracy: 0.3517 - val_loss: 1.4283 - val_categorical_accuracy: 0.4488
Epoch 5/50
137/137 [==============================] - 0s 1ms/step - loss: 2.0737 - categorical_accuracy: 0.3732 - val_loss: 1.3527 - val_categorical_accuracy: 0.4631
Epoch 6/50
137/137 [==============================] - 0s 1ms/step - loss: 1.7686 - categorical_accuracy: 0.3714 - val_loss: 1.2894 - val_categorical_accuracy: 0.4508
Epo

137/137 [==============================] - 0s 1ms/step - loss: 1.1369 - categorical_accuracy: 0.5130 - val_loss: 1.1049 - val_categorical_accuracy: 0.5348


In [14]:
forecasts = classifier.predict(X_test)
result =  classifier.evaluate(X_test, y_test)

51/51 [==============================] - 0s 863us/step - loss: 1.1241 - categorical_accuracy: 0.5335


In [15]:
y_test_transform = [np.argmax(t) for t in y_test]
forecasts_transform = [np.argmax(t) for t in forecasts]

precision = accuracy_score(y_test_transform, forecasts_transform)
print(precision)

0.5335384615384615


In [16]:
matrix = confusion_matrix(forecasts_transform, y_test_transform)
print(matrix)

[[  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]
 [  4  25 247 122  16   3   0]
 [  4  26 267 559 189  31   1]
 [  0   3   7  50  61  10   0]
 [  0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0]]
