In [14]:
import pandas as pd
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import np_utils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
import itertools
from sklearn.metrics import classification_report, plot_confusion_matrix
import seaborn as sns

In [15]:
data = pd.read_csv("wine_quality.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed.acidity         6497 non-null   float64
 1   volatile.acidity      6497 non-null   float64
 2   citric.acid           6497 non-null   float64
 3   residual.sugar        6497 non-null   float64
 4   chlorides             6497 non-null   float64
 5   free.sulfur.dioxide   6497 non-null   float64
 6   total.sulfur.dioxide  6497 non-null   float64
 7   density               6497 non-null   float64
 8   pH                    6497 non-null   float64
 9   sulphates             6497 non-null   float64
 10  alcohol               6497 non-null   float64
 11  quality               6497 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 609.2 KB


## Divisão de base de dados e separação de base

In [16]:
#attributes = data[["fixed.acidity","volatile.acidity","citric.acid","residual.sugar","chlorides","free.sulfur.dioxide","total.sulfur.dioxide","density","pH","sulphates","alcohol"]]
#quality = data[["quality"]]

In [18]:
classifier = Sequential()
classifier.add(Dense(units=32, activation="linear",input_dim=11))
classifier.add(Dropout(0.1))
classifier.add(Dense(units=16, activation="linear"))
classifier.add(Dropout(0.1))
classifier.add(Dense(units=10, activation="softmax"))
classifier.compile(optimizer="adam", loss="categorical_crossentropy",
                      metrics=["categorical_accuracy"])
history = classifier.fit(X_train, y_train, batch_size=32,
                  epochs=50,validation_split=0.1)

Epoch 1/50
137/137 [==============================] - 1s 3ms/step - loss: 8.9650 - categorical_accuracy: 0.3481 - val_loss: 2.0689 - val_categorical_accuracy: 0.4406
Epoch 2/50
137/137 [==============================] - 0s 2ms/step - loss: 4.6315 - categorical_accuracy: 0.3483 - val_loss: 2.0460 - val_categorical_accuracy: 0.4488
Epoch 3/50
137/137 [==============================] - 0s 2ms/step - loss: 2.9802 - categorical_accuracy: 0.3515 - val_loss: 1.3916 - val_categorical_accuracy: 0.4836
Epoch 4/50
137/137 [==============================] - 0s 2ms/step - loss: 2.3359 - categorical_accuracy: 0.3670 - val_loss: 1.3543 - val_categorical_accuracy: 0.4652
Epoch 5/50
137/137 [==============================] - 0s 2ms/step - loss: 1.9346 - categorical_accuracy: 0.3818 - val_loss: 1.2914 - val_categorical_accuracy: 0.4918
Epoch 6/50
137/137 [==============================] - 0s 2ms/step - loss: 1.7110 - categorical_accuracy: 0.4010 - val_loss: 1.2411 - val_categorical_accuracy: 0.4980
Epoc

In [19]:
forecasts = classifier.predict(X_test)
result =  classifier.evaluate(X_test, y_test)

51/51 [==============================] - 0s 1ms/step - loss: 1.1271 - categorical_accuracy: 0.5157


In [20]:
y_test_transform = [np.argmax(t) for t in y_test]
forecasts_transform = [np.argmax(t) for t in forecasts]

precision = accuracy_score(y_test_transform, forecasts_transform)
print(precision)

0.5156923076923077


In [21]:
matrix = confusion_matrix(forecasts_transform, y_test_transform)
print(matrix)

[[  0   0   0   0   0   0]
 [  0   0   0   0   0   0]
 [  5  30 338 197  20   4]
 [  6  25 206 465 209  42]
 [  1   0   3  33  35   6]
 [  0   0   0   0   0   0]]
